### PR TITLE
fix #4

### LINKED ISSUE #4: Room has no id bread Room.findAll
```shell
00:26:34 VERB Room findAll() rejected: no id
Error: no id
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet/src/puppet.ts:850:13)
    at Generator.next (<anonymous>)
    at /wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadchat.roomPayload (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:510:16)
    at AnotherOriginalClass.<anonymous> (/wechaty/src/user/room.ts:293:23)
    at Generator.next (<anonymous>)
    at /wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.ready (/wechaty/dist/src/user/room.js:241:16)
    at Promise.all.roomList.map.room (/wechaty/src/user/room.ts:128:27)
    at Array.map (<anonymous>)
    at Function.<anonymous> (/wechaty/src/user/room.ts:125:18)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/user/room.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Exception is thrown out when trying to get all the room payload. I think issue should be here:
https://github.com/Chatie/wechaty-puppet/blob/5b24558cc24fe1fc30178820467a7ffc41b047ea/src/puppet.ts#L829-L833

The id might be `undefined` or `null`, so in `roomPayload` function the error thrown out:
https://github.com/Chatie/wechaty-puppet/blob/5b24558cc24fe1fc30178820467a7ffc41b047ea/src/puppet.ts#L935-L942

Comparing to `contactSearch`
https://github.com/Chatie/wechaty-puppet/blob/5b24558cc24fe1fc30178820467a7ffc41b047ea/src/puppet.ts#L491-L507

I think we should do similar things for room, when error happens, catch it and log it, but not throw exception that breaks the whole process. 

Does this make sense to you @zixia ?

### PR DESCRIPTION
**Pull request by windmemory**

### CODE REVIEW

File: src/puppet.ts [hunk 1]
```diff
@@ -855,7 +855,15 @@ export abstract class Puppet extends EventEmitter {
 
     const roomPayloadList = await Promise.all(
```
Comment (zixia) [inline src/puppet.ts]: Please add a `.filter` to the `roomPayloadList` so that we will not get a `undefined` in the data.

File: src/puppet.ts [hunk 2]
```diff
@@ -853,11 +853,19 @@ export abstract class Puppet extends EventEmitter {
...
 
-    const roomPayloadList = await Promise.all(
+    const roomPayloadList: RoomPayload[] = (await Promise.all(
       allRoomIdList.map(
-        id => this.roomPayload(id),
+        async id => {
+          try {
+            return await this.roomPayload(id)
+          } catch (e) {
+            // compatible with {} payload
```
Comment (zixia) [inline src/puppet.ts]: If the room id is invalid, should we delete them from the cache so that we will not get the non-exist payload of that id again?

If so, I think the following code will get it done:

```ts
await this.roomPayloadDirty(id)
await this.roomMemberPayloadDirty(id)
```

Comment (zixia) [reply src/puppet.ts]: Glad to know that you can fix more, thank you very much.

Comment (windmemory) [reply src/puppet.ts]: Just updated my comment above, please take a look.

Comment (zixia) [reply src/puppet.ts]: Yes, I agree with you that the low-level data should be maintained by the puppet implementation, it's the responsibility of the puppet implementation,  and they should do well.

At the same time, I believe it's also necessary to clean the invalid data in puppet base class instead of leaving as it is.

Comment (windmemory) [reply src/puppet.ts]: Okay, I got it, will update the PR soon.

**Comment by windmemory** [comment]
Updated.

**Comment by zixia** [comment]
Awesome, LGTM.

Please get at least one approvement from the community for your PR before I could be able to merge it.

Thank you very much.

**Comment by windmemory** [comment]
There is only one contributor in this repository, how to get another Code Review?

**Comment by zixia** [comment]
I believe everyone can do a code review.

Just click the "File Changes" link on top of this PR, and then click the "Review Changes" button on the top right.

**Comment by windmemory** [comment]
Okay
